on: push
name: Mirror
jobs:
  codeberg:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v7
          with:
            fetch-depth: 0
        - uses: yesolutions/mirror-action@v0.7.0
          with:
            REMOTE: 'ssh://git@codeberg.org/JuliaUQ/UncertaintyQuantification.jl'
            GIT_SSH_PRIVATE_KEY: ${{ secrets.CODEBERG_PRIVATE }}
            GIT_SSH_NO_VERIFY_HOST: "true"